# Site settings
title: Sugey Medina
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sugey Medina
user_description: Soy una estudiante de innovación empresarial en cancún, en la universidad del Caribe. Con muchas ganas de aprender y seguir creciendo.
instagram_username: nsxlm_
facebook_username: Nahomi Loza 
github_username: Sukixlm
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

